project:
  type: website
  output-dir: docs

website:
  title: "Rajeshwari Periyaswamy"
  navbar:
    left:
      - href: index.qmd
        text: Welcome
      - href: Focus.qmd
        text: Focus
      - href: Unwind.qmd
        text: Unwind
      - href: Musing.qmd
        text: Musing
      

format:
  html:
    theme: 
      light: Sandstone
      dark: Slate
    css: styles.css
    toc: true



