project:
  type: website
  output-dir: docs

website:
  title: "Rajeshwari Periyaswamy"
  navbar:
    left:
      - href: index.qmd
        text: Welcome
      - Focus.qmd
      - Unwind.qmd
      - Musing.qmd
      

format:
  html:
    theme: 
      light: Sandstone
      dark: Slate
    css: styles.css
    toc: true



